CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(10) UNIQUE NOT NULL,
	password VARCHAR(10) NOT NULL,
	name VARCHAR(100) NOT NULL,
	admin BOOLEAN NOT NULL
);

CREATE TABLE products (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description VARCHAR(255),
	image VARCHAR(255),
	count INTEGER,
	price FLOAT
);

CREATE TABLE tags (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE productTags (
	productId INTEGER REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
	tagId INTEGER REFERENCES tags(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE shopping (
        id SERIAL PRIMARY KEY,
        date TIMESTAMP,
        userId INTEGER REFERENCES users(id) ON UPDATE CASCADE
);


CREATE TABLE purchasedProducts (
        id SERIAL PRIMARY KEY,
	amount FLOAT,
        productsId INTEGER REFERENCES products(id) ON UPDATE CASCADE,
	shoppingId INTEGER REFERENCES shopping(id) ON UPDATE CASCADE
);

)
